### ISSUE TITLE
conda environment issue

### ISSUE THREAD

**Issue by Mei0211** [Vchitect/VBench#1]
ERROR: Could not find a version that satisfies the requirement detectron2==0.6 (from versions: none)
ERROR: No matching distribution found for detectron2==0.6
can't pip install detectron2==0.6

**Comment by ziqihuangg** [comment]
Hi, you can try `pip install detectron2@git+https://github.com/facebookresearch/detectron2.git`

**Comment by Mei0211** [comment]
TY, but it still can't work

**Comment by ziqihuangg** [comment]
We've updated the installation instruction: https://github.com/Vchitect/VBench#hammer-installation Please let us know if you still encountered problems during installation.

**Comment by Mei0211** [comment]
TY for your great work!

**Comment by yinanhe** [comment]
It appears that the issue has been resolved, and the current issue is about to be closed. If you still have any questions, please feel free to reopen this issue at any time. 😊
