### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './VBench_full_info.json' 

### ISSUE THREAD

**Issue by chenerg** [Vchitect/VBench#10]
When using vbench installed with pip install, the error popped up.

**Comment by yinanhe** [comment]
I'm sorry you encountered this issue, you should download [VBench_full_info.json](https://[raw.githubusercontent.com/Vchitect/VBench/master/VBench_full_info.json] (https://raw.githubusercontent.com/Vchitect/VBench/master/VBench_full_info.json) and place it in the running directory.

**Comment by WhiteDOU** [comment]
[VBench_full_info.json](https://raw.githubusercontent.com/Vchitect/VBench/master/VBench_full_info.json)  is 404: Not Found

**Comment by ziqihuangg** [comment]
Hi, thanks for letting us know. The link is updated to: https://github.com/Vchitect/VBench/blob/master/vbench/VBench_full_info.json
The READMD is also update.
