### ISSUE TITLE
Evaluation data issues 

### ISSUE THREAD

**Issue by GFENGG** [Vchitect/VBench#12]
Hello, Is there an unified configs for the evaluation data (mp4 files), such as the fps, duration, resolution, and etc.

And does the different settings (such as duration and resolution) of mp4 files have an influence on the final evaluation results using VBench? I'm not sure about this.

**Comment by ziqihuangg** [comment]
Hi, thanks for your question! Currently the supported formats are GIF, MP4, and PNG. See this function for video loading: https://github.com/Vchitect/VBench/blob/master/vbench/utils.py#L101

VBench has already considered the influence from frame rate and resolution during evaluation.

For example, some dimensions can be sensitive to video frame rate, like "Dynamic Degree". For higher frame rate videos, the dynamics (movement) between two consecutive frames are generally smaller, resulting in a false result of "low dynamic degree". Therefore, we eliminate frame rate's influence at the preprocessing step: https://github.com/Vchitect/VBench/blob/master/vbench/dynamic_degree.py#L86C9-L86C19

So during evaluation, you can directly supply the raw video without any preprocessing to VBench, and VBench will take care of any preprocessing needed for individual evaluation dimensions.
