### ISSUE TITLE
generating videos from images

### ISSUE THREAD

**Issue by cyy-1234** [Vchitect/VBench#13]
Hello, author. After reading your paper, I have some doubts about certain details. May I directly input a video clip (without any prompts) for evaluation? Is your method applicable to generating videos from images? Looking forward to your response.

**Comment by yinanhe** [comment]
Thank you for your interest in our work. VBench provides `video quality dimensions` that are relevant to the input text. You can only test relevant dimensions.
 [
  "subject consistency",
  "background consistency",
  "temporal flickering",
  "motion smoothness",
  "aesthetic quality",
  "imaging quality",
  "dynamic degree",]

**Comment by cyy-1234** [comment]
hello，Are there any requirements for the naming of the generated video, such as '{prompt}-{index}.mp4'? Is this format necessary?

**Comment by cyy-1234** [comment]
![image](https://github.com/Vchitect/VBench/assets/59501159/8cb58f0c-ceb0-4c42-a444-5c0016678f42)
hi,Why do we need to subtract one?

**Comment by yinanhe** [comment]
> hello，Are there any requirements for the naming of the generated video, such as '{prompt}-{index}.mp4'? Is this format necessary?

We have not updated the code to read frames directly for the time being, so such naming is necessary, or you can modify the code to read in frames as needed

**Comment by yinanhe** [comment]
> ![image](https://private-user-images.githubusercontent.com/59501159/305800528-8cb58f0c-ceb0-4c42-a444-5c0016678f42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMjIwMDcsIm5iZiI6MTcwODMyMTcwNywicGF0aCI6Ii81OTUwMTE1OS8zMDU4MDA1MjgtOGNiNThmMGMtY2ViMC00YzQyLWE0NDQtNWMwMDE2Njc4ZjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDA1NDgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNjkwNTdlZjEyNzQ4ODY5NTM5NzYwMjk1Y2M2YzdhY2JhMjljZmU3OThlN2VjNTlmMmUxNmVjNWQ0NGJlMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FgmSA_gbY27BOANEvq1N5eHqu4qmQQ_oa5xxYvBa6_E) hi,Why do we need to subtract one?

When calculating the `subject consistency` dimension, the consistency between the current frame and the previous frame and the consistency between the current frame and the first frame are calculated, the total number of computations is `num_frames -1`

**Comment by cyy-1234** [comment]
Hi，author，
![image](https://github.com/Vchitect/VBench/assets/59501159/32aefc33-2559-4b18-9f05-309b74b77ca0)
I have successfully executed the evaluation with only video, and the results for 'background_consistency,' 'temporal_flickering,' 'motion_smoothness,' 'aesthetic_quality,' 'imaging_quality,' and 'dynamic_degree' seem to be fine. 
![image](https://github.com/Vchitect/VBench/assets/59501159/e04431fe-08fa-4258-92d7-a2320bf1cbc5)
The only area of confusion lies in the 'subject_consistency' aspect，Two numerical values are inconsistent.
![image](https://github.com/Vchitect/VBench/assets/59501159/e3094931-ebb4-49e8-9644-620417da47df)

**Comment by cyy-1234** [comment]
![image](https://github.com/Vchitect/VBench/assets/59501159/f89179c5-dd2c-4ea0-90e1-236c12b9b001)
![image](https://github.com/Vchitect/VBench/assets/59501159/1d86b029-5ed4-4379-8c77-dbcc827c1022)
![image](https://github.com/Vchitect/VBench/assets/59501159/236d4c9e-5aa6-4b24-85a7-02ed2e38f586)


**Hi, when I run multiple videos at once to calculate aesthetic_quality, I always get the error 'CUDA out of memory.' What could be the reason? According to my understanding, the model should only load one video at a time, and the size of the input videos is  small.**

**Comment by yinanhe** [comment]
This does not seem normal, you need to check your local environment

**Comment by ziqihuangg** [comment]
> Hello, author. After reading your paper, I have some doubts about certain details. May I directly input a video clip (without any prompts) for evaluation? Is your method applicable to generating videos from images? Looking forward to your response.

@cyy-1234 Hi, please check out VBench-I2V for evaluating image-to-video models: https://github.com/Vchitect/VBench/tree/master/vbench2_beta_i2v

**Comment by ziqihuangg** [comment]
Hi, we're closing this issue as it appears your questions have been addressed. However, feel free to open a new issue or reopen this one, if you have further questions or if anything else comes up related to this issue.

**Comment by Crazy-wu-20** [comment]
> ![image](https://private-user-images.githubusercontent.com/59501159/305879506-f89179c5-dd2c-4ea0-90e1-236c12b9b001.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzA3NzYsIm5iZiI6MTcxODM3MDQ3NiwicGF0aCI6Ii81OTUwMTE1OS8zMDU4Nzk1MDYtZjg5MTc5YzUtZGQyYy00ZWEwLTkwZTEtMjM2YzEyYjliMDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDEzMDc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0NTg0M2ZlYzEyODYyMjc4NDA5MmZlODAyMDYyODk2MmYwOTJlZDQ3NjdhNTMzOGM3ZGU5N2M4NzkyZmRlYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MoatefTGXEpXKD7mc4p65_mrKB7cmpodyw43y9UHGlM) ![image](https://private-user-images.githubusercontent.com/59501159/305879625-1d86b029-5ed4-4379-8c77-dbcc827c1022.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzA3NzYsIm5iZiI6MTcxODM3MDQ3NiwicGF0aCI6Ii81OTUwMTE1OS8zMDU4Nzk2MjUtMWQ4NmIwMjktNWVkNC00Mzc5LThjNzctZGJjYzgyN2MxMDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDEzMDc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YmNmM2UzMjI0OTQxMjI4NDhhNTJjNzE3OTJhYjEyMzJkN2QxODRjYmY1ODA4Mjg0ODY1OTI0ZTM1ZTYwNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.doL3setR7JzozPDnLD1hR6fMu6PLXRYNeT2XJef1VHY) ![image](https://private-user-images.githubusercontent.com/59501159/305879792-236d4c9e-5aa6-4b24-85a7-02ed2e38f586.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzA3NzYsIm5iZiI6MTcxODM3MDQ3NiwicGF0aCI6Ii81OTUwMTE1OS8zMDU4Nzk3OTItMjM2ZDRjOWUtNWFhNi00YjI0LTg1YTctMDJlZDJlMzhmNTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDEzMDc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MGFiN2FmMTdmYjQ4ZjQ0YTY2N2RjNjA4NjQ0M2M4YjQ4MTQyYjNkMTk1Zjc5OGNmMDU2YTg3ZmYzNzRlMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mNkWss8fbX8ZwSoGZDq3QRgGsmr_hYugoCSHR24Ac8g)
> 
> **Hi, when I run multiple videos at once to calculate aesthetic_quality, I always get the error 'CUDA out of memory.' What could be the reason? According to my understanding, the model should only load one video at a time, and the size of the input videos is small.**

Hi, have you solved this question? I have the same problem.

**Comment by ziqihuangg** [comment]
Hi, may I ask what's your video length (in seconds)? It's possible that the frame count caused OOM
