### ISSUE TITLE
how to execute the project ? 

### ISSUE THREAD

**Issue by ParvAggarwal** [Vchitect/VBench#14]
its great effort from the authors. can anyone tell step by step explanation to run the project. your effort will be highly appreciated.

**Comment by yinanhe** [comment]
Sorry for the late reply. 
The simplest way is to follow these steps: 
1. Install VBench by running `pip install vbench`. 
2. Generate the corresponding videos based on the dimensions listed in the [prompts list](https://github.com/Vchitect/VBench/tree/master/prompts) or using the [all dimension](https://github.com/Vchitect/VBench/blob/master/prompts/all_dimension.txt). 
3. Save the [VBench_full_info.json](https://github.com/Vchitect/VBench/blob/master/VBench_full_info.json) file in the current directory. 
4. Use the command `vbench evaluate --videos_path $VIDEO_PATH --dimension $DIMENSION` in the command line. 
5. Find the results for the corresponding dimension in the `evaluation_results` directory.

**Comment by ziqihuangg** [comment]
Since there is no more follow-up questions for a while, I'm closing the issue. Feel free to re-open it if you encounter more issues in executing the project.
