### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './VBench_full_info.json'

### ISSUE THREAD

**Issue by JHL328** [Vchitect/VBench#15]
when running !vbench evaluate --videos_path "..." --dimension "...." encounter file NOT FOUND
and the link you put in the repo for VBench_full_info.json will turn to 404

**Comment by JHL328** [comment]
sloved, you should check your super link for VBench_full_info.json. It should be https://github.com/Vchitect/VBench/blob/master/vbench/VBench_full_info.json

**Comment by ziqihuangg** [comment]
Thanks for that! Already fixed README.
