### ISSUE TITLE
how to use detectron2(which require torch<=1.10) and the torch>=1.12 in requirement

### ISSUE THREAD

**Issue by JHL328** [Vchitect/VBench#16]
as the title

**Comment by yinanhe** [comment]
detectron2 requires torch<=1.8.0
![image](https://github.com/Vchitect/VBench/assets/43169235/d96f1512-faad-4c70-a751-82c37bafae39)

**Comment by ziqihuangg** [comment]
Hi, we're closing this issue as it appears your questions have been addressed. However, feel free to open a new issue or reopen this one, if you have further questions or if anything else comes up related to this issue.
