### ISSUE TITLE
provide the pretrained weights for reproducing the results in leaderboard

### ISSUE THREAD

**Issue by GFENGG** [Vchitect/VBench#18]
Hello, can you provide the model weights and project for reproducing the results in leaderboard?
Thank you so much.

**Comment by yinanhe** [comment]
Which model's pretraining weight is it? We all get the weight or video from the corresponding project's official project page.

**Comment by GFENGG** [comment]
> Which model's pretraining weight is it? We all get the weight or video from the corresponding project's official project page.

For example: [VideoCrafter-1.0](https://github.com/AILab-CVC/VideoCrafter/tree/VideoCrafter1?tab=readme-ov-file)

**Comment by ziqihuangg** [comment]
Hi, please find the model details here: https://github.com/Vchitect/VBench/tree/master/sampled_videos#what-are-the-details-of-the-video-generation-models
