### ISSUE TITLE
What does the result means?

### ISSUE THREAD

**Issue by chenerg** [Vchitect/VBench#19]
`
{
    "imaging_quality": [
        0.6686933368155237,
        [
            {
                "video_path": "/data/*.mp4",
                "video_results": 56.49358892440796
            },
`

This is part of the result. I can see that video_results is the imaging_quality score, but what does '0.6686933368155237' means?

**Comment by yinanhe** [comment]
`0.6686933368155237` is the overall score of `imaging_quality`

**Comment by chenerg** [comment]
Thanks! That solved!
