### ISSUE TITLE
sample_per_video function related

### ISSUE THREAD

**Issue by Mei0211** [Vchitect/VBench#2]
Could you give an example of the sample_per_video function? Thanks！

**Comment by ziqihuangg** [comment]
Hi, this is the function to sample a video, from the model you want to evaluate.

**Comment by Mei0211** [comment]
Excuse me, could you upload the model and sample script used in the paper or send it privately? Thank you so much!


1585421442
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Vchitect/VBench"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月19日(星期五) 中午12:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Vchitect/VBench] sample_per_video function related (Issue #2)





 
Hi, this is the function to sample a video, from the model you want to evaluate.

**Comment by ziqihuangg** [comment]
Hi, you can refer to the open-sourced sampling code for each video generation model. For instance, to sample from the LaVie model, you can use this script: https://github.com/Vchitect/LaVie/blob/main/base/pipelines/sample.py, and the sampling instruction is here: https://github.com/Vchitect/LaVie/tree/main?tab=readme-ov-file#step1-base-t2v

Hope this clarified your question, thanks!

**Comment by ziqihuangg** [comment]
Hi, we've added detailed information for each models' sampling settings: https://github.com/Vchitect/VBench/tree/master/sampled_videos#what-are-the-details-of-the-video-generation-models

I'm closing the issue as there has been no follow-up questions for a while, but feel free to re-open it anytime if you still have any related questions.
