### ISSUE TITLE
Where can I find open source video data?

### ISSUE THREAD

**Issue by Mei0211** [Vchitect/VBench#21]
Thanks for your great work, I want to know where can I find those generated videos mentioned in the paper?

**Comment by ziqihuangg** [comment]
Hi, we have organised and uploaded the sampled videos here: https://drive.google.com/drive/folders/13pH95aUN-hVgybUZJBx1e_08R6xhZs5X?usp=sharing

You can follow the example scripts here for automatic download and evaluation: https://github.com/Vchitect/VBench?tab=readme-ov-file#example-of-evaluating-videocrafter-10

**Comment by ziqihuangg** [comment]
Hi, more details regarding open-sourced video data is provided here: https://github.com/Vchitect/VBench/tree/master/sampled_videos#sampled-videos

**Comment by ziqihuangg** [comment]
Hi, we're closing this issue as it appears your questions have been addressed. However, feel free to open a new issue or reopen this one, if you have further questions or if anything else comes up related to this issue.
