### ISSUE TITLE
LeaderBoard code

### ISSUE THREAD

**Issue by GFENGG** [Vchitect/VBench#25]
Hello, Do you have a plan to release the code for the LeaderBoard?

**Comment by ziqihuangg** [comment]
Leaderboard code is available at https://huggingface.co/spaces/Vchitect/VBench_Leaderboard/tree/main.

**Comment by ziqihuangg** [comment]
These results are already displayed in the leaderboard. Thanks.

**Comment by GFENGG** [comment]
> These results are already displayed in the leaderboard. Thanks.

emmm, I means the raw results before showing in the leaderboard, 
because the results in the leaderboard are normalized and weighted summed.

If i want to launch a gradio in a local environment, it is necessary to get the results.csv in the CSV_DIR.
So can you provide the  results.csv used in the leaderboard?

Thank you very much.

**Comment by GFENGG** [comment]
> These results are already displayed in the leaderboard. Thanks.

Hello, I find some dimensions are missed in the upload sampled videos, 
for example, videocrafter-1.tar.gz don not have the dimension of "background consistency",

**Comment by ziqihuangg** [comment]
Hi, for missing videos: Some dimensions, such as "background consistency" and "scene," use the same set of videos.

plus: It would be great if you open new issues for each question or email us for ongoing discussions. Thanks!

**Comment by GFENGG** [comment]
Thanks，i will try with the same video sets，and i will open a new issue if i have other questions.在 2024年4月29日，11:23，Ziqi Huang ***@***.***> 写道：﻿
Hi, for missing videos: Some dimensions, such as "background consistency" and "scene," use the same set of videos.
plus: It would be great if you open new issues for each question or email us for ongoing discussions. Thanks!

**Comment by GFENGG** [comment]
> Hi, for missing videos: Some dimensions, such as "background consistency" and "scene," use the same set of videos.
> 
> plus: It would be great if you open new issues for each question or email us for ongoing discussions. Thanks!

Thanks，i will try with the same video sets，and i will open a new issue if i have other questions
