### ISSUE TITLE
run inference on customized video and prompt?

### ISSUE THREAD

**Issue by rebuttalpapers** [Vchitect/VBench#27]
I understand we can run inference on customized video (as in https://github.com/Vchitect/VBench/issues/7).
However, can we run inference on both customized video and prompt?

**Comment by ziqihuangg** [comment]
Yes. 
By "customized video," we mean videos that are generated based on text prompts provided by users, rather than using the text prompts from VBench's Prompt Suite.

**Comment by ziqihuangg** [comment]
Hi, I'm closing the issue as there's no follow-up questions, but feel free to re-open it anytime if you have any further questions!
