### ISSUE TITLE
pretrained/umt_model

### ISSUE THREAD

**Issue by Mei0211** [Vchitect/VBench#3]
Is there a model.txt file missing in the umt_model folder? Do I need to download it?

**Comment by yinanhe** [comment]
Sorry for the late response, thank you for pointing out this error. For now, you can download the corresponding model by executing `wget https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/umt/single_modality/l16_ptk710_ftk710_ftk400_f16_res224.pth -P  ~/.cache/vbench/umt_model`. We will supplement this file as soon as possible.

**Comment by yinanhe** [comment]
We have updated it at https://github.com/Vchitect/VBench/blob/master/pretrained/umt_model/model_path.txt. If there are still issues, please feel free to reopen this issue at any time.
