### ISSUE TITLE
the score meaning

### ISSUE THREAD

**Issue by Jason-xin** [Vchitect/VBench#31]
hello, what's the meaning of 0.9351381915230905?

![image](https://github.com/Vchitect/VBench/assets/13817995/369a5591-4d46-47c5-a495-731fb7175e7c)

**Comment by yinanhe** [comment]
The score for this dimension, which has been normalized to a range of 0-1.

**Comment by ziqihuangg** [comment]
Hi, we're closing this issue as it appears your questions have been addressed. However, feel free to open a new issue or reopen this one, if you have further questions or if anything else comes up related to this issue.
