### ISSUE TITLE
Division by 0 when directory only contains a single video

### ISSUE THREAD

**Issue by htnico** [Vchitect/VBench#37]
Hi,

When the input directory contains a single video asset, this [line](https://github.com/Vchitect/VBench/blob/master/vbench/subject_consistency.py#L56) will throw an exception related to division by 0:
```
sim_per_video = sim / (len(video_list) - 1)
```
I believe it should be
```
sim_per_video = sim / len(video_list)
```
Can you confirm that's the case?

**Comment by ziqihuangg** [comment]
Hi, this is a bug and we've fixed it! Thanks for pointing it out.
