### ISSUE TITLE
Pika, Gen2 latest results

### ISSUE THREAD

**Issue by somepago** [Vchitect/VBench#39]
First of all, thank you for creating this benchmark. It is an important contribution. I see both Pika and Gen-2 results are quite old. I’m wondering if it’s possible to update those numbers just to see how far open source models are behind the close source models. Thanks!

**Comment by ziqihuangg** [comment]
Hi, thanks for this question. We are actually in the middle of evaluating the latest Gen-2 and Pika. The results will be updated to our leaderboard.

**Comment by somepago** [comment]
Thanks. I'm assuming you will be adding SVD as well.

**Comment by ziqihuangg** [comment]
Hi, SVD is already in the VBench-I2V leaderboard.
