### ISSUE TITLE
Great works. A question about detailed inference settings for animatediffv2.

### ISSUE THREAD

**Issue by jiaxiangc** [Vchitect/VBench#44]
Hi, we are testing animatediffv2 model in your benchmark. Here are some questions.
1. We see you provied a lora link, but i find it is realistic checkpoint v5.1 (unet not lora weights.)
2. What is your inference steps.
We want to reproduce a similar results for animatediffv2, but the results are so far from the benchmark results.

**Comment by ziqihuangg** [comment]
Hi, the detailed setting for sampling is recorded here: https://github.com/Vchitect/VBench/tree/master/sampled_videos#what-are-the-details-of-the-video-generation-models
Feel free to let us know any further questions.

**Comment by jiaxiangc** [comment]
Here is a lora link that you provide. But i find it is a checkpoint, not a lora.
https://civitai.com/models/4201?modelVersionId=130072
When you inference animatediffv2, what unet model you use?

**Comment by jiaxiangc** [comment]
By the way, how to calculate total score? I compute the average score, the results are 64.67 (but 80+ in huggingface). Does it weighted value?

**Comment by DZY-irene** [comment]
> Here is a lora link that you provide. But i find it is a checkpoint, not a lora. https://civitai.com/models/4201?modelVersionId=130072 When you inference animatediffv2, what unet model you use?

Hello, we are using the `configs/prompts/v2/v2-1-RealisticVision.yaml ` for generation. Here are our settings:
```

- inference_config: "configs/inference/inference-v2.yaml"
  motion_module:    "models/Motion_Module/mm_sd_v15_v2.ckpt"

  dreambooth_path: "models/DreamBooth_LoRA/realisticVisionV60B1_v51VAE.safetensors"
  lora_model_path: ""

  seed:           2 #[13100322578370451493, 14752961627088720670, 9329399085567825781, 16987697414827649302]
  steps:          25
  guidance_scale: 7.5

  prompt: # VBench_prompt
  n_prompt:
    - "semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, text, close up, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck"

```
Please download the `Pruned Model fp16 (1.99 GB)` from https://civitai.com/models/4201?modelVersionId=130072 and place it in the corresponding directory, then set its path in `dreambooth_path`.

**Comment by jiaxiangc** [comment]
@DZY-irene @ziqihuangg 
Get it.
Do you know how to compute total score? It is not averaged score for 16 dimension scores.

**Comment by jiaxiangc** [comment]
@DZY-irene @ziqihuangg Hi, what is the correct json format？
The results are abnormal. How to withdraw it？https://huggingface.co/spaces/Vchitect/VBench_Leaderboard
All results are 0.

**Comment by jiaxiangc** [comment]
@ziqihuangg @DZY-irene 
Thanks for your work.
Here are some question for submit.
1. How to fill in "source"? When I upload the .zip files, the "source" is user upload.
2. What is the correct json format. 
The following are our results in a json file. We upload a zip directory containing 16 dimension json file. But the results are 0.
![image](https://github.com/Vchitect/VBench/assets/76088379/bf1ea9a2-3215-4d8a-86ec-40786011c896)
3. How to delete upload history? The results are abnormal....
Best wishes.

**Comment by yinanhe** [comment]
@jiaxiangc  For "source," you can fill it in the "team name." For "source," you can fill it in the "team name."
![image](https://github.com/Vchitect/VBench/assets/43169235/a43337b7-f0ab-46df-9272-321f2b44dd8b)

**Comment by jiaxiangc** [comment]
@yinanhe Thanks, I get it.
