### ISSUE TITLE
Can we withdraw the results in leaderboard？

### ISSUE THREAD

**Issue by jiaxiangc** [Vchitect/VBench#46]
We do not know how to compute total score. If we submit results in leaderboad, can we withdraw it?

**Comment by ziqihuangg** [comment]
Hi, it's already withdrawn from our side. If you would like to upload again, it would be great to provide the full information of your model. Thanks!

**Comment by jiaxiangc** [comment]
I just want to know the score calculation rules.

**Comment by ziqihuangg** [comment]
See this issue: https://github.com/Vchitect/VBench/issues/9

**Comment by jiaxiangc** [comment]
@ziqihuangg Hi, what is the correct json format？
The results are abnormal. How to withdraw it？https://huggingface.co/spaces/Vchitect/VBench_Leaderboard

**Comment by yinanhe** [comment]
I have already answered your question on HuggingFace. If you still have issue, feel free to open this issue at any time. At the same time, we have updated the offline script. See in #45.
