### ISSUE TITLE
About sampled videos

### ISSUE THREAD

**Issue by Qiulin-W** [Vchitect/VBench#5]
Hi, great work!

Will the sampled videos from different video generation models be released?  Especially the videos generated by Gen-2 and Pika.

Thanks!

**Comment by yinanhe** [comment]
Certainly! We've already uploaded sample videos of `lavie`, `modelscope`, `videocrafter0.9`, and `cogvideo` on [Hugging Face](https://huggingface.co/datasets/Vchitect/VBench_sampled_video/tree/main), along with their corresponding human annotations available at [this link](https://huggingface.co/datasets/Vchitect/VBench_human_annotation). The sampled videos of `Gen-2` and `Pika` are still being organized for evaluation. We will update the results and release the corresponding videos and annotations ASAP.

**Comment by Qiulin-W** [comment]
Thank！
