### ISSUE TITLE
Difference between "overall_consistency" and "temporal_style"?

### ISSUE THREAD

**Issue by 7thChord** [Vchitect/VBench#54]
Dear Authors, 

Thank you for the good work and the codes.

We were just wondering the difference between "overall_consistency" and "temporal_style". These two metrics appear to have respective .py codes under "vbench" dir. By text matching, they are basically identical other than function names. Our result validates our guess - they are always the same in these two metrics.

Interestingly, these two values seem different in README demo. Any suggestion and/or clarification would be greatly appreciated. Thank you very much.

**Comment by ziqihuangg** [comment]
Hi, thanks for the question. Both dimensions use ViCLIP to measure video-text similarity. The difference is the text prompts, where "temporal style" uses a diverse list of temporal styles including variations in motion speed, camera movements, and dynamic effects. These temporal styles are combined with several scenarios to evaluate whether the model can generate a particular scenario under different temporal styles. On the other hand, overall consistency uses a list of general prompts under different content categories and scenarios.

**Comment by 7thChord** [comment]
Thank you very much. I found the problem. We were following "evaluate your own videos" and these two metrics shouldn't be included.
