### ISSUE TITLE
Implementation Details

### ISSUE THREAD

**Issue by lovelyczli** [Vchitect/VBench#57]
Thank you for your excellent work on VBench, which has been very inspiring to me.

When I attempted to reproduce the results in Table 1 of your paper using video samples generated by my ModelScope code, instead of the samples you provided, I encountered significant discrepancies, with the performance being much lower than the reported results. Could you provide more details about the generation models, beyond what is mentioned in the supplementary materials? This information is really important to me.

Models              height, width      num_frames    fps   inference_steps      guidance_scale      seed
LaVie--------      256×256             16                    8             250                    7                           2
ModelScope                 512×512         16                    8                  ???                       ?                         ?
VideoCrafter      256×256             16                   8               ???                      ?                                2
CogVideo---        480×480              33                  10                ???                     ?                              2

I look forward to your response. Whether or not you can provide all the details, please let me know.

**Comment by lovelyczli** [comment]
@ziqihuangg

**Comment by ziqihuangg** [comment]
Please refer to the model details here: https://github.com/Vchitect/VBench/tree/master/sampled_videos#what-are-the-details-of-the-video-generation-models
Let me know if there is other specific information you are looking for.

**Comment by lovelyczli** [comment]
Thank you for your response.

In addition to the information provided, could you also share details regarding inference_steps, guidance_scale, and seed?

num_inference_steps controls the number of denoising steps, with higher steps generally leading to better video quality
guidance_scale represents the guidance scale value, where a higher value typically increases the relevance of the generated video to the text prompt, but might decrease image quality.

These parameters are crucial for video generation quality as well.

@ziqihuangg @JustinYuu

**Comment by JustinYuu** [comment]
@lovelyczli Hi, thanks for your interest in our work!

For the modelscope videos, we use the officially provided modelscope.pipelines API for sampling, where the seed, inference steps, and the guidance scale are not able to be viewed and adjusted. To reproduce our generation results, you could try to use the same modelscope package and model as shown in the code example part of the following [link](https://modelscope.cn/models/iic/text-to-video-synthesis/file/view/master?fileName=README.md&status=1).

**Comment by lovelyczli** [comment]
Got it, thank you for the quick response and the great work!
