### ISSUE TITLE
Unrecognized arguments: --mode=custom_input when running vbench

### ISSUE THREAD

**Issue by ChengYoghurt** [Vchitect/VBench#62]
Hello,
thanks for your great work!

I'm having trouble running the command provided in the instruction:

> vbench evaluate \
    --dimension $DIMENSION \
    --videos_path /path/to/folder_or_video/ \
    --mode=custom_input

The error output message I got was:

> vbench: error: unrecognized arguments: --mode=custom_input

So, I wonder, is it because vbench installed directly from pip does not support customized input videos?

**Comment by NattapolChan** [comment]
Hi, Can you check the version of the vbench. Is it installed from pypi or installed from source?
