### ISSUE TITLE
Opensoraplan-v1.1  score

### ISSUE THREAD

**Issue by LWang1016** [Vchitect/VBench#67]
@lmxyy @xjxu21 @piddnad @JustinYuu @simplaj ,
Hi, every, I just evaluate the Opensoraplan-v1.1 score with your provided videos and evaluation toolkit. But I can not get the same score as your report in the leadboard.  
Besieds, I also evaluate the opensorav1.0, also with your provided videos and toolkit, and can get the same score.  
I want to make sure for the Opensoraplan-v1.1 results, do you use the released videos for evaluation?

Thanks very much.

**Comment by ziqihuangg** [comment]
May I ask which evaluation pipeline did you use for evaluation? Is it VBench or VBench-Long? Thanks!

**Comment by LWang1016** [comment]
VBench

**Comment by LWang1016** [comment]
here is my evaluation results.
<img width="1419" alt="截屏2024-09-06 16 22 34" src="https://github.com/user-attachments/assets/9cc08d21-cc1a-4d0e-8b7b-70d747fd4b8d">

**Comment by LWang1016** [comment]
@MqLeet. I just download  your released generated videos to do the metric evaluation.

**Comment by MqLeet** [comment]
Hi, @LWang1016, we will close this issue. 

Feel free to contact us if you have other questions.
