### ISSUE TITLE
Questions about the input prompts used in CogVideoX-5B (SAT prompt-optimized)

### ISSUE THREAD

**Issue by maozezhong** [Vchitect/VBench#89]
When evaluating,  Prompts used in CogVideoX-5B (SAT prompt-optimized) is optimized? Can you provide the prompt used in CogVideoX's evalutation?

**Comment by ziqihuangg** [comment]
Yes, we applied the prompt optimisation pipeline according to CogVideoX's instructions. More details and the optimized prompt list can be found here: https://github.com/Vchitect/VBench/tree/master/prompts/gpt_enhanced_prompts

**Comment by maozezhong** [comment]
thanks for your promply reply！another question
The optimzied prompts are only used in generating videos OR used in both generate and calculate vbench score?

**Comment by ziqihuangg** [comment]
Optimised prompts are only used to sample videos. The VBench evaluation still uses the original prompt before optimization.
