### ISSUE TITLE
how to calculate the total score of all metircs

### ISSUE THREAD

**Issue by xinyuxiao** [Vchitect/VBench#9]
thank you very much!

**Comment by yinanhe** [comment]
Thank you for your interest in VBench. You can refer to the calculation scheme at [Get Total Score](https://huggingface.co/spaces/Vchitect/VBench_Leaderboard/blob/72b2069d0022f09f270393139dd39a86c57250cd/app.py#L82-L88) to calculate the standardized scores and weighted scores of different dimensions, obtaining quality scores and semantic scores. Then, sum them up to get the total score. 

Alternatively, you can upload evaluation results for all dimensions, which will be calculated by the Leaderboard.

**Comment by xinyuxiao** [comment]
ok，thanks

**Comment by jiaxiangc** [comment]
> Thank you for your interest in VBench. You can refer to the calculation scheme at [Get Total Score](https://huggingface.co/spaces/Vchitect/VBench_Leaderboard/blob/72b2069d0022f09f270393139dd39a86c57250cd/app.py#L82-L88) to calculate the standardized scores and weighted scores of different dimensions, obtaining quality scores and semantic scores. Then, sum them up to get the total score.
> 
> Alternatively, you can upload evaluation results for all dimensions, which will be calculated by the Leaderboard. We will add this feature directly into the code of VBench as soon as possible.

Hi, do you add this feature in the code now？ Thanks
